### ISSUE TITLE
ReversoTranslate TypeError

### ISSUE THREAD

**Issue by Vioshim** [Animenosekai/translate#3]
Good morning, today I've been testing a bit with the module with my application, and realized that some string sequences can lead to the translate function to output the following.

```cmd
Traceback (most recent call last):
  File "c:\Users\Vioshim\Desktop\Parser\tests\test.py", line 7, in <module>
    print(translator.translate(text='', destination_language='Spanish'))
  File "C:\Users\Vioshim\Desktop\Parser\env\lib\site-packages\translatepy\translate.py", line 75, in 
translate
    lang, response = self.reverso_translate(text, destination_language, source_language)
TypeError: 'ReversoTranslate' object is not callable
```

This happens when attempting to translate a string that doesn't contain words, such as `""` or `"\n"` rather than returning the string itself.

In my code, I handle it currently by catching the exception, however I decided to mention the inconvenient as I'm not sure if it is intended.

Example code:
```py
from translatepy import Translator

translator = Translator()
print(translator.translate(text='    ', destination_language='Spanish'))
```

Have a good day

**Comment by Animenosekai** [comment]
Hello and thank you for your detailed reports!

I fixed it and uploaded the new version on PyPI!

Indeed, it had a problem with the `ReversoTranslate` class being called instead of the `ReversoTranslate.translate` method.

You can update your `translatepy` installation now with `pip install --upgrade translatepy`

Check that you have the new version with `python3 -c "import translatepy; print(translatepy.__version__)"` (or the python version that you have).   
It should display: `translatepy v1.1.3`
