### ISSUE TITLE
When install from git won't download some classes

### ISSUE THREAD

**Issue by davidmartinrius** [Animenosekai/translate#34]
Hello!!

I wanted to use translate_html method. As you told me yesterday I have to use the option 2: from git
pip install --upgrade git+https://github.com/Animenosekai/translate

First of all I did pip uninstall translatepy to ensure no conflicts with the old code. After this, I executed 
pip install --upgrade git+https://github.com/Animenosekai/translate

Unfortunatelly, there are missing some classes inside translate.py file like 
from translatepy.translators
from translatepy.utils.annotations import List
from translatepy.utils.queue import Queue
from translatepy.utils.request import Request
from translatepy.utils.sanitize import remove_spaces

I know I could copy and paste the missing code from github, but for me it would be a dirty way to solve it.

Is there a good way to solve it? 

Thank you so much!

David

**Comment by ZhymabekRoman** [comment]
Hmmm, strange behavior, I tried installing from git in my new venv environment and everything worked fine. I am using Linux by the way, what OS do you have?

I don't know how to solve the problem, but I suggest a workaround - instead of downloading repositories from Git, download the zip file generated by GitHub: pip3 install --upgrade https://github.com/Animenosekai/translate/archive/refs/heads/main.zip

**Comment by davidmartinrius** [comment]
Hello, today a installed a fresh translate and it works well. I don't know why happened. In any case, I think I can close this ticket. Thank you!
