### ISSUE TITLE
SSL verification warning when using Reverso dictionary

### ISSUE THREAD

**Issue by joeperpetua** [Animenosekai/translate#55]
When using ReversoTranslate service dictionary() function, a SSL warning from urllib3 is thrown about making a nonverified HTTPS request to context.reverso.net:

```
Python 3.9.1 (tags/v3.9.1:1e5d33e, Dec  7 2020, 17:08:21) [MSC v.1927 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> from translatepy.translators.reverso import ReversoTranslate
>>> t = ReversoTranslate()
>>> t.dictionary("casa", "eng")
C:\Users\xxxx\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\connectionpool.py:1013: InsecureRequestWarning: Unverified HTTPS request is being made to host 'context.reverso.net'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  warnings.warn(
DictionaryResult(service=Reverso, source=casa, source_language=spa, destination_language=eng, result=['house', 'home', 'place', 'cottage', 'household', 'villa', 'apartment', 'family', 'residence', 'flat', 'company', 'pad', 'homestead', 'firm', 'hearth', 'habitation', 'fireside', 'married', 'marries', 'gaff', 'Casa'])
```

When using the translate() function, this is not thrown:
```
Python 3.9.1 (tags/v3.9.1:1e5d33e, Dec  7 2020, 17:08:21) [MSC v.1927 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> from translatepy.translators.reverso import ReversoTranslate
>>> t = ReversoTranslate()
>>> t.translate("casa", "eng")
TranslationResult(service=Reverso, source=casa, source_language=spa, destination_language=eng, result=house)
```

Checking the urllib3 docs it seems that the certificate verification is now enabled by default starting from version 1.25. A worlaround would be to manually disable it:

```
import urllib3
urllib3.disable_warnings()
```

But maybe there is a nicer way of managing this.

**Comment by ZhymabekRoman** [comment]
Hmmm, yeah, this is a familiar problem. A few months ago, some Reverso's subdomains had some problems with SSL certificate, maybe out of date, in short, didn't pass the verification, because of that the library became useless, tests also crashed with an error (here are the tests that crashed with an error, alas logs are not saved - https://github.com/Animenosekai/translate/runs/3754458905?check_suite_focus=true)
Because of that I had to turn off the SSL certificate check - https://github.com/Animenosekai/translate/commit/20fed9255b857c08d19566e800af0df58893e42c. There seems to be no problem with certificates at the moment. I created a PR to rollback the change - #56
