### ISSUE TITLE
How reliable is this library?

### ISSUE THREAD

**Issue by spamz23** [Animenosekai/translate#8]
First of all, nice work!
I would like to implement this in some of my projects. However I would like to know if this is reliable (you are using some API Keys), or you are using workarounds, which might stop working at any time.

PS: This is not really an issue, but rather a question.

**Comment by Animenosekai** [comment]
Hey and thank you for having an interest on my project!

This module is indeed using "workarounds" (if you want to call them like that): it is using the APIs used on the official websites.

Sometimes they might not work (Yandex and DeepL for example have a very strict Rate Limit policy), but that's why this project exists: It uses the different APIs and fallbacks to one API or another if something goes wrong. This is why I'm considering it on PyPI as "Stable".

Using the `Translator()` class (which groups the APIs), I've never experienced any sorts of bug.

If you want further information, please let me know!

**Comment by spamz23** [comment]
I forked your project and started to take a deeper look at the code. I spotted possible refactorings that could make the code more bug-free, and also increase the scalability (e.g. If you are adding more translators).
Would you be interested in a PR?

**Comment by Animenosekai** [comment]
Sure, I'll check the PR!
